spring:
  datasource:
    url: jdbc:h2:mem:taskease
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

logging:
  level:
    org.springframework.web: DEBUG