spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskease_db
    username: postgres
    password: SimonVriesema
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        web-allow-others: false

logging:
  level:
    org.springframework.web: DEBUG

server:
  servlet:
    session:
      timeout: 30m