spring:
  datasource:
    url: jdbc:h2:mem:taskease
    username: sa
    password: my_secure_password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

logging:
  level:
    org.springframework.web: DEBUG

server:
  servlet:
    session:
      timeout: 30m