name: CI Pipeline for TaskEaseAPI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  setup-jdk:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

  build:
    runs-on: ubuntu-latest
    needs: setup-jdk
    steps:
      - name: Build with Maven
        run: mvn clean install

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run tests with Maven
        run: mvn test